name: ğŸš€ DEV Build

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write  # nÃ©cessaire pour push GHCR depuis le workflow appelÃ©

jobs:
  build:
    uses: brege-ng/infra_devops_pipelines/.github/workflows/build-manual.yml@main
    with:
      dockerfile: ./Dockerfile
      context: .
