name: ğŸš€ PROD Build

on:
  push:
    branches:
      - main
      - release
  workflow_dispatch:

permissions:
  contents: read
  packages: write  # <- attention, GitHub bloque si repo externe privÃ©

jobs:
  build:
    uses: cabinet-ceipi/infra-devops-pipelines/.github/workflows/build-auto.yml@main
    with:
      dockerfile: ./Dockerfile
      context: .
