name: ðŸš€ DEV Build

on:
  workflow_dispatch:

jobs:
  build:
    uses: brege-ng/infra_devops_pipelines/.github/workflows/build-manual.yml@main
    with:
      dockerfile: ./Dockerfile
      context: .
